[package]
name = "feder-runtime-server"
description = "Runnable server runtime for Feder on standard operating systems."
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
feder-core = { workspace = true, features = ["http-signatures"] }
feder-vocab.workspace = true
iri-string.workspace = true
axum = "0.8"
httpdate = "1"
ipnet = "2.11.0"
serde.workspace = true
thiserror = "2"
serde_json.workspace = true
percent-encoding = "2.3.2"
rand_core.workspace = true
reqwest = { version = "0.13.1", default-features = false, features = ["rustls"] }
rusqlite = { version = "0.40.1", features = ["bundled"] }
tokio = { version = "1", features = ["net"] }
url = "2"

[dev-dependencies]
serde_json.workspace = true
tokio = { version = "1", features = ["macros", "net", "rt-multi-thread", "sync"] }
tower.workspace = true

[lints]
workspace = true
