[package]
name = "ref-feder-runtime-server"
description = "Experimental reference implementation of Feder's server runtime."
publish = false
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
ref-feder-core.workspace = true

[lints]
workspace = true
