[package]
name = "ref-feder-runtime-server"
description = "Experimental reference implementation of Feder's server runtime."
publish = false
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
axum = "=0.8"
feder-vocab.workspace = true
httpdate = "1"
mime = "0.3.17"
percent-encoding = "2.3.2"
ref-feder-core = { workspace = true, features = ["http-signatures"] }
reqwest = {
    version = "0.13.1",
    default-features = false,
    features = ["rustls"],
}
serde.workspace = true
serde_json.workspace = true
thiserror = "2.0.19"
url = "2"
ipnet = "2.11.0"
tokio = { version = "1", features = ["net"] }

[lints]
workspace = true
