[package]
name = "ref-feder-core"
description = "Experimental reference implementation of Feder's protocol core."
publish = false
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[features]
http-signatures = ["dep:base64", "dep:rsa", "dep:zeroize"]

[dependencies]
base64 = { workspace = true, optional = true }
feder-vocab.workspace = true
rsa = { workspace = true, optional = true }
zeroize = { workspace = true, optional = true }

[lints]
workspace = true
