[package]
name = "feder-core"
description = "Portable ActivityPub core logic for Feder."
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[features]
http-signatures = ["dep:rsa", "dep:zeroize"]

[dependencies]
feder-vocab.workspace = true
rsa = { workspace = true, optional = true }
zeroize = { workspace = true, optional = true }

[dev-dependencies]
rand_chacha.workspace = true

[lints]
workspace = true
